export default {
  'project/get': {
    content: [
      {
        id: 1,
        status: 2,
        name: 'Цөм сүргийн төв',
        activity: 'Үржил',
        budget: '32,281 ам.доллар',
        duration: '60 сар',
        date: 'Jun 25, 2021, 12:03 PM',
      },
      {
        id: 2,
        status: 5,
        name: 'Цөм сүргийн төв 4',
        activity: 'Үржил',
        budget: '32,281 ам.доллар',
        duration: '5 сар',
        date: 'Jun 25, 2021, 12:03 PM',
      },
      {
        id: 3,
        status: 4,
        name: 'Цөм сүргийн төв 5',
        activity: 'Мал',
        budget: '32,281 ам.доллар',
        duration: '1 сар',
        date: 'Jun 25, 2021, 12:03 PM',
      },
      {
        id: 4,
        status: 3,
        name: 'Цөм сүргийн төв 7',
        activity: 'Үржил',
        budget: '32 ам.доллар',
        duration: '40 сар',
        date: 'Jun 25, 2021, 12:03 PM',
      },
      {
        id: 5,
        status: 1,
        name: 'Цөм сүргийн төв 9',
        activity: 'Үржил',
        budget: '32,281 ам.доллар',
        duration: '60 сар',
        date: 'Jun 25, 2021, 12:03 PM',
      },
    ],
    pageable: {
      sort: {
        sorted: false,
        unsorted: true,
        empty: true,
      },
      offset: 0,
      pageNumber: 0,
      pageSize: 25,
      paged: true,
      unpaged: false,
    },
    totalPages: 1,
    totalElements: 8,
    last: true,
    size: 25,
    number: 0,
    sort: {
      sorted: false,
      unsorted: true,
      empty: true,
    },
    numberOfElements: 8,
    first: true,
    empty: false,
  },
};
