export default {
  '/gap-report-service/reportGroups': {
    content: [
      {
        status: true,
        originId: null,
        createdAt: '2021-07-23 07:37:04',
        updatedAt: null,
        deletedAt: null,
        createdBy: 9,
        updatedBy: null,
        deletedBy: null,
        id: 1,
        name: 'Төвлөрүүлэн захирагч',
        isActive: true,
        priority: 0,
      },
      {
        status: true,
        originId: null,
        createdAt: '2021-07-23 07:39:37',
        updatedAt: '2021-07-27 03:00:10',
        deletedAt: null,
        createdBy: 9,
        updatedBy: 9,
        deletedBy: null,
        id: 2,
        name: 'Засгийн газар болон орон нутгийн тусгай сан',
        isActive: true,
        priority: 0,
      },
      {
        status: true,
        originId: null,
        createdAt: '2021-07-27 03:13:11',
        updatedAt: null,
        deletedAt: null,
        createdBy: 9,
        updatedBy: null,
        deletedBy: null,
        id: 4,
        name: 'Сангийн мэдээлэл',
        isActive: true,
        priority: 0,
      },
      {
        status: true,
        originId: null,
        createdAt: '2021-07-27 03:15:29',
        updatedAt: null,
        deletedAt: null,
        createdBy: 9,
        updatedBy: null,
        deletedBy: null,
        id: 5,
        name: 'Төрийн өмчийн ААНБ',
        isActive: true,
        priority: 1,
      },
      {
        status: true,
        originId: null,
        createdAt: '2021-07-27 03:16:22',
        updatedAt: null,
        deletedAt: null,
        createdBy: 9,
        updatedBy: null,
        deletedBy: null,
        id: 6,
        name: 'Салбар төсвийн ерөнхийлөн захирагч',
        isActive: true,
        priority: 2,
      },
      {
        status: true,
        originId: null,
        createdAt: '2021-07-27 03:17:32',
        updatedAt: null,
        deletedAt: null,
        createdBy: 9,
        updatedBy: null,
        deletedBy: null,
        id: 7,
        name: 'ААНБ, ТББ, Иргэн',
        isActive: true,
        priority: 3,
      },
      {
        status: true,
        originId: null,
        createdAt: '2021-07-27 03:17:53',
        updatedAt: '2021-07-28 17:23:38',
        deletedAt: null,
        createdBy: 9,
        updatedBy: 9,
        deletedBy: null,
        id: 8,
        name: 'Нийгмийн даатгалын ерөхий газар',
        isActive: true,
        priority: 5,
      },
      {
        status: true,
        originId: null,
        createdAt: '2021-07-27 03:18:05',
        updatedAt: '2021-07-28 17:23:22',
        deletedAt: null,
        createdBy: 9,
        updatedBy: 9,
        deletedBy: null,
        id: 9,
        name: 'Сангийн яам',
        isActive: true,
        priority: 6,
      },
    ],
    pageable: {
      sort: {
        sorted: false,
        unsorted: true,
        empty: true,
      },
      offset: 0,
      pageNumber: 0,
      pageSize: 25,
      paged: true,
      unpaged: false,
    },
    totalPages: 1,
    totalElements: 8,
    last: true,
    size: 25,
    number: 0,
    sort: {
      sorted: false,
      unsorted: true,
      empty: true,
    },
    numberOfElements: 8,
    first: true,
    empty: false,
  },
};
